-  pricing--
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-service
  name: kafka-service1
  namespace: kafka
spec:
  type: NodePort
  ports:
  - name: kafka-port
    port: 9092
    nodePort: 30091
    targetPort: 9092
  selector:
    app: kafka
    id: "1"

