---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka1-service
  name: kafka1-service
  namespace: kafka
spec:
  type: NodePort
  ports:
  - name: kafka-port
    port: 9092
    nodePort: 30091 # to connect from the outside world
    targetPort: 9092
  selector:
    app: kafka
    id: "1"
