---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: kafka
  name: kafka-1
  namespace: kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
        id: "1"
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka1-service.kafka.svc.cluster.local"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181"
        - name: KAFKA_CREATE_TOPICS
          value: "test-topic:1:1"
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        name: kafka
        ports:
        - containerPort: 9092
