---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka3-service
  name: kafka3-service
  namespace: kafka
spec:
  type: NodePort
  ports:
  - name: kafka-port
    port: 9092
    # nodePort: 30093, not need to use a specific one
    targetPort: 9092
  selector:
    app: kafka
    id: "3"
