---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: kafka
  name: kafka-3
  namespace: kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
        id: "3"
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "192.168.99.100"
        - name: KAFKA_ADVERTISED_PORT
          value: "30093"
        - name: KAFKA_BROKER_ID
          value: "3"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 192.168.99.100:30181
        - name: KAFKA_CREATE_TOPICS
          value: "test-topic:3:3"
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        name: kafka
        ports:
        - containerPort: 9092

