apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kafka-monitor
  namespace: kafka-ca1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-monitor
  template:
    metadata:
      labels:
        app: kafka-monitor
    spec:
      containers:
      - name: kafka-monitor
        image: d1egoaz/docker-kafka-monitor@sha256:aa9d1bae75f3a6f6714953a72d6c326065d6571641c9b196aaa19a3a335d332c
        imagePullPolicy: Always
        ports:
        - name: gui
          containerPort: 8000
        - name: metrics
          containerPort: 8778
        - name: jmx
          containerPort: 9999
        resources:
          limits:
            cpu: 125m
            memory: 500Mi
          requests:
            cpu: 125m
        command: [ "/bin/bash", "-c", "--" ]
        args: ["tail -f /dev/null"]
