apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kafka-monitor
  namespace: kafka-ca1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-monitor
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka-monitor
    spec:
      automountServiceAccountToken: false
      containers:
      - name: kafka-monitor
        image: d1egoaz/docker-kafka-monitor@sha256:26ec3eed294c007a6d285f95550960ee55b1358c7432b574e4fd91ab3c6676d1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 125m
            memory: 500Mi
          requests:
            cpu: 125m
        command: [ "/bin/bash", "-c", "--" ]
        args: ["tail -f /dev/null"]
        volumeMounts:
          - name: kafka-monitor-volume
            mountPath: /opt/kafka-monitor/config/kafka-monitor.properties
            subPath: kafka-monitor.properties
          - name: log4j-volume
            mountPath: /opt/kafka-monitor/config/log4j.properties
            subPath: log4j.properties
      volumes:
        - name: kafka-monitor-volume
          configMap:
            name: kafka-monitor-volume
        - name: log4j-volume
          configMap:
            name: log4j-volume
