kind: Service
apiVersion: v1
metadata:
  name: kafka-monitor
  namespace: kafka-ca1
spec:
  type: NodePort
  selector:
    app: kafka-monitor
  ports:
  - name: gui
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: metric
    port: 8778
    protocol: TCP
    targetPort: 8778
  - name: jmx
    port: 9999
    protocol: TCP
    targetPort: 9999
