kind: Service
apiVersion: v1
metadata:
  name: kafka-manager
  namespace: kafka
spec:
  type: NodePort
  selector:
    app: kafka-manager
  ports:
  - nodePort: 31317
    port: 9000
    protocol: TCP
    targetPort: 9000
